apiVersion: v1
kind: Template
labels:
  template: buildah
metadata:
  annotations:
    description: buildah container
    iconClass: buildah
    tags: instant-app
  name: buildah
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: buildah
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: buildah
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: buildah:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/CentOS-PaaS-SIG/linchpin.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/s2i/jenkins/buildah
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: develop
